apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: membrillo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: membrillo
  labels: { app: mysql }
spec:
  replicas: 1
  strategy: { type: Recreate }   # un solo pod sobre un PVC RWO
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: membrillo-secrets, key: MYSQL_ROOT_PASSWORD } }
            - name: MYSQL_DATABASE
              valueFrom: { configMapKeyRef: { name: membrillo-config, key: MYSQL_DATABASE } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits: { memory: "512Mi" }
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: mysql-pvc }
        - name: initdb
          configMap: { name: membrillo-sql }   # creado por deploy.ps1 desde ../sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: membrillo
spec:
  selector: { app: mysql }
  ports:
    - port: 3306
      targetPort: 3306
